### ISSUE TITLE
Clear ViewModel in iOS

### ISSUE THREAD

**Issue by stef-ang** [petros-efthymiou/DailyPulse#13]
Hey Petros! I bought your course in Udemy. it's awesome.

But, in the BaseViewModel for iOS, you created a clear function to clear the coroutine scope and you never used it

Would be great to see an example of where it could be used, please

**Comment by petros-efthymiou** [comment]
Thanks.
I have updated the final branch the use the clear function. It's happening in the "onDisappear" iOS View callback functions.
